### PR TITLE
feature: add Cloudinary file-upload service

### LINKED ISSUE #26: Experiment with media storage
Find a good solution for storing media files.

### PR DESCRIPTION
**Pull request by DaveDangereux**
The purpose of this feature is to allow resource submissions to include attachments that will be separately stored using Cloudinary, while metadata for uploaded attachments is generated and saved to the database.

In order to achieve this, we have a few new moving parts.

**middleware/fileParser & jsonParser**
-

Both of these middlewares are application-wide and are run immediately after `express.json()` (the old bodyParser).

`fileParser` is an instance of `multer` and is used to parse requests with multipart form-data (as opposed to raw JSON which `express.json()` handles). `multer` takes any form fields that are set to submit text and places them in `req.body` (much like if bodyParser were parsing JSON key-value pairs). `multer` will also take any form fields that are set to submit files and parse these, placing the results in `req.files` (as the `fileParser` middleware is set to handle multiple files at once).

The upshot of this is that if we POST some form-data and send some files with Postman, we will have access to them in `req.files`.

This does leave the puzzle of how to submit our original JSON data that we would otherwise have sent as raw JSON, as the submission must be either form-data or raw JSON - not both.

The best solution I could find is to submit the JSON data as a string in a text field and have another piece of middleware parse this field as JSON and replace `req.body` with it. This is what the `jsonParser` middleware does.

So if you submit raw JSON, you can pick it up in `req.body`. But if you submit form-data with a 'json' field as a string and some files in a separate field, you can still pick up your JSON in `req.body` and your files will be in `req.files`.

Great, we've got files and we haven't had to mess with our existing controller code too much (just wait, though).

`fileParser` is also where acceptable file types are set, using an object whose keys are all accepted mime-types and whose values are set to one of the broader category of attachment types ('file', 'image', 'video'). Within `fileParser`, this object is only used by `multer` to filter out file types we're not interested in. However, this object is also exported for use with `cloudinary`, where it is used to generate metadata (for easy grouping of attachment types for later rendering in React).

**loaders/cloudinaryLoader**
-

The `cloudinary` object is imported in `server.js` and passed to a loader function to configure it. It's not entirely clear to me what the advantage of passing it to the loader function is (rather than, say, importing `cloudinary` separately in the loader and calling the loader function in `server.js` without passing anything in). I suspect it has something to do with dependency injection which I still don't understand. But it's not broken, so possibly I shouldn't fix it?

**services/cloudinaryService**
-

Additionally to the loader, we also have `cloudinaryService`, which is a set of Cloudinary crud functions I have hastily swept into a convenient module to prevent any controller function from mutating into a ravenous pile of spaghetti.

I may be taking liberties calling this a 'service'. It definitely doesn't follow the 'repository pattern'. Ultimately however, the goal is to make this functionality reusable in other controllers as need be. Presently, I've only implemented attachment uploading on the Learning Resource controller, but even if it later seemed appropriate to generalise it via the universal crud functions, I think it's still neater to have cloud crud wrapped up in its own little box where it can't hurt anyone we know or care about.

`cloudinaryService` provides three functions:

`addFiles`: takes an array of multer-parsed files, uploads it to Cloudinary and returns metadata for uploading to the database.

`removeFiles`: takes an array of metadata and deletes those files from Cloudinary.

And then there's `updateFiles`...

`updateFiles` takes three arguments:

`newMetadata`: any submitted file metadata from `req.body.attachments` (including a blank array, which is differentiated from `undefined`)

`oldMetadata`: the metadata from the document retrieved from the database (`doc.attachments`)

`files`: an array of files from `req.files`. 

If new metadata exists, it compares it to the old metadata to see what might have been removed, then removes those files from Cloudinary. If files were submitted, it uploads them. It then aggregates a revised set of metadata and returns it for updating the database.

This might well be a daft way to implement a PUT request that also needs to cascade updates to a third-party service, but I was imagining that we might have some state in React where our metadata was living and, upon removing a file, might then update the metadata on the database with _whatever was left_. And for Cloudinary to then reflect that, a PUT request should be able to submit any combination of existing attachment metadata back to the server and have only those attachments preserved on Cloudinary. This also means that all attachments could be removed by submitting a blank array for the 'attachment' field.

PUT requests seem a little tricky to me, because they can involve any combination of adding or removing attachments. I've attempted the most sensible implementation I can think of, but if you have a better idea then I'm very keen to take it onboard.

Probably after some sleep, though.

Let me know what you think.

You'll need to add three values to your `.env` files:

`CLOUDINARY_CLOUD_NAME`

`CLOUDINARY_API_KEY`

`CLOUDINARY_API_SECRET`

All of which are available from the dashboard after creating a free Cloudinary account.

Cheers m'dears.

### CODE REVIEW

**Comment by DaveDangereux** [comment]
Forgot to mention, I'm using mongoose's findByIdAndDelete / Update instead of deleteOne and updateOne. As a result, my delete and update controller functions send the whole document back to the client. This is currently inconsistent with the universal crud functions, but was preferable at the time.

Without diving into another verbose explanation (which I would happily do, but I'm concerned about exhausting anyone's patience), I am happy to change this to be consistent with the universal crud, but also curious to know whether this alternative behaviour might be preferable more generally.

**Comment by DaveDangereux** [comment]
Alright folks, ignore all that garbage up top - that was a dry-run.

New file-upload solution in place - much more sensible and hopefully more fault-tolerant.

Probably still some holes to plug here and there.

I've included a sample .env to fill in with your own MongoDB connection string and Cloudinary details.

If you want to upload files when creating / updating a LearningResource, attach them as a form field labelled 'files' (in Postman you'll need to set the field to 'File' rather than 'Text'). Multi-file upload is supported - just include multiple fields all labelled 'files'. JSON data can accompany this request in a separate field labelled 'json' (this is primarily so that you can pass sub-documents as values - if you're just passing primitive values, adding them as fields in the form data is fine).

If you want to delete files when performing an update, pass the file '_id' values as an array of strings in a field labelled 'attachmentsToDelete'.

See you on Wednesday.

**Comment by D4n93r3ux** [comment]
Hmm... there's a bunch of file changes in this commit that I didn't make and I'm slightly confused as to how they got there. Oh well, one to figure out after work I guess...

**Review by admtomas — APPROVED** [review]

**Comment by admtomas** [comment]
All good

**Pull request merged**
